### ISSUE TITLE
what fflags are for the weird movement

### ISSUE THREAD

**Issue by NoobLikesThis** [d44df016fe28bc8d5974/rbxflags#3]

**Comment by d44df016fe28bc8d5974** [comment]
what do you mean

**Comment by NoobLikesThis** [comment]
the weird movement fflag doesnt say which noclip or low gravity

**Comment by d44df016fe28bc8d5974** [comment]
https://streamable.com/ymoeek

**Comment by d44df016fe28bc8d5974** [comment]
{
    "DFIntDebugSimPrimalLineSearch": "1",
    "DFIntDebugSimPrimalWarmstartForce": "160",
    "DFIntDebugSimPrimalWarmstartVelocity": "102",
    "FFlagDebugSimDefaultPrimalSolver": "True"
}

**Comment by NoobLikesThis** [comment]
ik, but what noclip or low grav ones are there bc theres 2 low gravs and 3 noclips

**Comment by d44df016fe28bc8d5974** [comment]
noclip 3 is the best one
unlike the other ones
with primal noclip you can interact with ingame stuff

**Comment by NoobLikesThis** [comment]
i mean for weird movement

**Comment by d44df016fe28bc8d5974** [comment]
i think i somehow pasted in different fflags instead of the ones in the video
which i did not save

**Comment by NoobLikesThis** [comment]
oh

**Comment by d44df016fe28bc8d5974** [comment]
@NoobLikesThis i lost the original fflags but i have recreated the same effect 
https://streamable.com/om4l5x

**Comment by d44df016fe28bc8d5974** [comment]
"DFIntDebugSimPrimalLineSearch": "1",
  "DFIntDebugSimPrimalWarmstartVelocity": "100",
  "DFIntDebugSimPrimalStiffness": "-50",
  "DFIntDebugSimPrimalStiffnessMax": "-20",
  "DFIntDebugSimPrimalStiffnessMin": "-10",
  "FFlagDebugSimDefaultPrimalSolver": "True"

**Comment by d44df016fe28bc8d5974** [comment]
just dont get stuck inside walls

**Comment by d44df016fe28bc8d5974** [comment]
update:
you only need these for the fly to work

  "DFIntDebugSimPrimalLineSearch": "1",
  "DFIntDebugSimPrimalWarmstartVelocity": "100",
  "FFlagDebugSimDefaultPrimalSolver": "True"

WarmstartVelocity is the fly fflag
you can't change it or you wont be able to fly

**Comment by NoobLikesThis** [comment]
oh
