### ISSUE TITLE
fullbright  fflag description copy and paste for fullbright 1 and 2

### ISSUE THREAD

**Issue by NoobLikesThis** [d44df016fe28bc8d5974/rbxflags#5]
###### tip: change the DFIntDebugFRMQualityLevelOverride fflag to 0 when you dont want quality 1 and wanna change it in game, best to hide ur fullbright while someone is watching.
``` json
{
"iaddallfflagshere": "no"
}
```

**Comment by d44df016fe28bc8d5974** [comment]
i have added the descriptions
