### ISSUE TITLE
noclips

### ISSUE THREAD

**Issue by NoobLikesThis** [d44df016fe28bc8d5974/rbxflags#6]
###### dont climb stairs, dont jump, buggy.
``` json
{
"DFIntDebugSimPrimalLineSearch": "1",
"DFIntDebugSimPrimalWarmstartVelocity": "102",
"DFIntDebugSimPrimalWarmstartForce": "25",
}
```
###### dont jump and buggy a bit.
``` json
{
"DFIntDebugSimPrimalLineSearch": "1",
"DFIntDebugSimPrimalWarmstartVelocity": "102",
"DFIntDebugSimPrimalWarmstartForce": "50",
}
```

**Comment by d44df016fe28bc8d5974** [comment]
you forgot to add the primal solver fflag which enables it

**Comment by d44df016fe28bc8d5974** [comment]
i will only add noclip 8 as noclip 7,8 are basically the same thing but warmstart has a slightly higher value

**Comment by NoobLikesThis** [comment]
yh

**Comment by NoobLikesThis** [comment]
> you forgot to add the primal solver fflag which enables it

roblox enables by default

**Comment by d44df016fe28bc8d5974** [comment]
> > you forgot to add the primal solver fflag which enables it
> 
> roblox enables by default

![image](https://github.com/user-attachments/assets/e91f048f-cb17-49c9-8fd7-a1b2e6e566a1)
looks like not

**Comment by NoobLikesThis** [comment]
huh??? it does for me

**Comment by d44df016fe28bc8d5974** [comment]
maybe the are a/b testing it somehow
but i don't think so
you probably have the fflag hidden somewhere in your list
