### ISSUE TITLE
incorrect fflag

### ISSUE THREAD

**Issue by NoobLikesThis** [d44df016fe28bc8d5974/rbxflags#8]
normal:
###### the teleporting is clientsided, no one else can see them
```json
{
    "DFIntGameNetLocalSpaceMaxSendIndex: "10000"
}
```
fixed:
###### the teleporting is clientsided, no one else can see them
```json
{
    "DFIntGameNetLocalSpaceMaxSendIndex": "10000"
}
```
code: 
```
{
    "DFIntGameNetLocalSpaceMaxSendIndex": "10000"
}
```

**Comment by d44df016fe28bc8d5974** [comment]
the " is there i don't know why the red color is there

**Comment by d44df016fe28bc8d5974** [comment]
![image](https://github.com/user-attachments/assets/4a95cc15-17b0-491b-b038-7636e5deb1ed)

**Comment by d44df016fe28bc8d5974** [comment]
fixed
